### ISSUE TITLE
Inquiry on Mel Spectrogram Level Attack 

### ISSUE THREAD

**Issue by rxpwang** [rainavyas/prepend_acoustic_attack#2]
Hi, thank you for the great work! I have learned a lot from your project and code. I noticed that you implemented the attack at the mel spectrogram level, but I couldn't find a corresponding discussion in the paper. Could you share some insights on the rationale behind this approach?

I'm curious whether attacking at the mel spectrogram level is less practical compared to attacking raw audio in practice. Intuitively, it seems that an attack at the mel spectrogram level might be more effective since it is one step "closer" to the output compared to raw audio.

Any insights or experiences you could share would be greatly appreciated.

**Comment by rainavyas** [comment]
Hi,

Thank you for the positive feedback. We are pleased the work has been useful! 

Yes, your intuition is correct: attacks in the log-mel space can be made more effective as the Whisper encoder can be presented with unnatural/impossible log-mel spectrograms which can allow for more effective attacks. However, the unnaturalness of the log-mel spec attack is actually a problem. The unnaturalness comes in the form disjoint jumps in the energy values across the frames (log-mel vectors across frequencies at each time step) along the time axis. However, it is impossible for real audio to generate such a log-mel spectrogram, as the frames in the log-mel spec represent time-windows from the real audio with an overlap. Therefore, despite training a vocoder to map the log-mel attack to the raw audio space, we are unable to preserve the log-mel spec attack. Therefore, as a real adversary should only have access to the raw audio input and a log-mel spec attack cannot be transferred (at least by our efforts) to the raw audio space, we conclude that a log-mel spec attack is not a real threat for ASR models...

**Comment by rxpwang** [comment]
Hi,

Thank you for the swift and informative response! It makes sense that the learned mel spectrogram attack cannot be properly transferred to the raw audio space.

I have a quick follow-up question: I noticed that the default mel attack size is 32, which corresponds to 0.32 seconds, compared to 0.64 seconds for the raw audio attack. Is there a specific reason for this setting? Have you observed any patterns in the selection of the mel attack size?

Thank you again for your insights.

**Comment by rainavyas** [comment]
Good spot! 0.32 seconds just happended to be a good operating point for the log-mel space attacks to ensure almost 100% attack success rate . However, this length of attack is not as strong in the raw-audio space... we ran an ablation and the results can be seen in Figure 3 of the paper on arxiv.

**Comment by rxpwang** [comment]
Thank you for your kind reply! I will close this issue as I have no further questions for now.
