### ISSUE TITLE
NeMo is not included in setup environment

### ISSUE THREAD

**Issue by GreyDGL** [rainavyas/prepend_acoustic_attack#5]
I tried to follow the installation process but encounter the error: `ModuleNotFoundError: No module named 'nemo'`. 
I then tried to install the package separately, but encounter some compatibility issues with the original environment. May I know the nemo version you used, and also could you please update the installation process to reflect this?

**Comment by GreyDGL** [comment]
Seems like the installation process is not updated together with the new attack on canary.

**Comment by rainavyas** [comment]
Hi,

Thanks for raising this - good spot. 
Here is the NEMO version used: `nemo_toolkit==1.23.0`

However, I would mention that I eventually did not run the attack on Canary - this is work in progress. Happy for anyone to extend the attack functionalities of Whisper for Canary.

**Comment by rainavyas** [comment]
And here is the update for environment: #6

**Comment by GreyDGL** [comment]
Appreciated the prompt response and thanks for this great work! Btw I love your paper too:)
