### ISSUE TITLE
Trying to run the codes

### ISSUE THREAD

**Issue by Trinita21** [rainavyas/prepend_acoustic_attack#7]
Hi. I have been trying to run the codes and there are so many version errors that it is very difficult to try and reproduce this project.  There are so many library version problems. Something is wrong with the environment file as not all the packages used are compatible ones. It would be great if you can update the repo so that there are less issues and debugging becomes easy.

**Comment by rainavyas** [comment]
Hi thanks for your question.

Please try the following:

```
conda env create -f environment_py310.yml
conda activate env_py310
```

This should allow you to run the training without any dependency errors.
